version: "3"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: kbdb
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: pg_password
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    ports:
      - 3000:3000

volumes:
  postgres: ~
